
CREATE TABLE public.participants (
    birth_date date,
    height integer,
    weight integer,
    s_name character varying(120),
    rank character varying(120),
    f_name character varying(120),
    participant_id integer NOT NULL,
);

CREATE VIEW public.participants_full AS
 SELECT participants.birth_date,
    participants.height,
    participants.weight,
    participants.s_name,
    participants.rank,
    participants.f_name,
    participants.participant_id
   FROM public.participants;

ALTER TABLE public.participants ALTER COLUMN participant_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.participants_participant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.results (
    result_id integer NOT NULL,
    date date,
    participant_id integer NOT NULL,
    score integer NOT NULL
);
ALTER TABLE public.results OWNER TO postgres;

CREATE VIEW public.results_full AS
 SELECT results.date,
    participants.f_name,
    participants.s_name,
    results.participant_id,
    results.score
   FROM (public.results
     LEFT JOIN public.participants ON ((participants.participant_id = results.participant_id)));


ALTER TABLE public.results ALTER COLUMN result_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.results_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.trainers (
    trainer_id integer NOT NULL,
    s_name character varying(120) NOT NULL,
    birth_date date,
    f_name character varying(120) NOT NULL
);

CREATE VIEW public.trainers_full AS
 SELECT trainers.s_name,
    trainers.f_name,
    trainers.birth_date
    trainers_rank
   FROM public.trainers;


CREATE TABLE public.training (
    training_id integer NOT NULL,
    participant_id integer NOT NULL,
    trainer_id integer NOT NULL
);

CREATE VIEW public.training_full AS
 SELECT participants.s_name,
    participants.f_name,
    trainers.s_name AS trainer_s_name,
    trainers.f_name AS trainer_f_name
   FROM ((public.training
     LEFT JOIN public.participants ON ((participants.participant_id = training.participant_id)))
     LEFT JOIN public.trainers ON ((trainers.trainer_id = training.trainer_id)));


ALTER TABLE public.training ALTER COLUMN training_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.training_training_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.participants
    ADD CONSTRAINT participant_id PRIMARY KEY (participant_id);


ALTER TABLE ONLY public.results
    ADD CONSTRAINT result_id PRIMARY KEY (result_id);


ALTER TABLE ONLY public.trainers
    ADD CONSTRAINT trainer_id PRIMARY KEY (trainer_id);


ALTER TABLE ONLY public.training
    ADD CONSTRAINT training_id PRIMARY KEY (training_id);


CREATE INDEX fki_participant_id ON public.training USING btree (participant_id);


CREATE INDEX fki_trainer_id ON public.training USING btree (trainer_id);


CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


ALTER TABLE ONLY public.training
    ADD CONSTRAINT participant_id FOREIGN KEY (participant_id) REFERENCES public.participants(participant_id);


ALTER TABLE ONLY public.results
    ADD CONSTRAINT participant_id FOREIGN KEY (participant_id) REFERENCES public.participants(participant_id);


ALTER TABLE ONLY public.training
    ADD CONSTRAINT trainer_id FOREIGN KEY (trainer_id) REFERENCES public.trainers(trainer_id);
